import type { StudioConfig } from '@/types/studios'

export const STUDIOS: StudioConfig[] = [
  {
    slug: 'chat',
    nameAr: 'استوديو المحادثة',
    nameEn: 'Chat Studio',
    descriptionAr: 'محادثة ذكية مع AI بأنواع مساعدين متعددة — عام، برمجة، أعمال، دراسة',
    category: 'text',
    icon: '💬',
    color: '#6366f1',
    gradient: 'from-indigo-500 to-purple-600',
    href: '/studios/chat',
    isActive: true,
    isPremium: false,
    sortOrder: 1,
  },
  {
    slug: 'articles',
    nameAr: 'استوديو المقالات',
    nameEn: 'Articles Studio',
    descriptionAr: 'كتابة مقالات احترافية — SEO، تقنية، تسويقية، تعليمية',
    category: 'text',
    icon: '✍️',
    color: '#10b981',
    gradient: 'from-emerald-500 to-teal-600',
    href: '/studios/articles',
    isActive: true,
    isPremium: false,
    sortOrder: 2,
  },
  {
    slug: 'translation',
    nameAr: 'استوديو الترجمة',
    nameEn: 'Translation Studio',
    descriptionAr: 'ترجمة احترافية بين العربية والإنجليزية — أكاديمية، تسويقية، تقنية',
    category: 'text',
    icon: '🌐',
    color: '#3b82f6',
    gradient: 'from-blue-500 to-cyan-600',
    href: '/studios/translation',
    isActive: true,
    isPremium: false,
    sortOrder: 3,
  },
  {
    slug: 'research',
    nameAr: 'استوديو الأبحاث',
    nameEn: 'Research Studio',
    descriptionAr: 'مساعدة أكاديمية للطلاب والباحثين — رسائل ماجستير ودكتوراه',
    category: 'research',
    icon: '🎓',
    color: '#f59e0b',
    gradient: 'from-amber-500 to-orange-600',
    href: '/studios/research',
    isActive: true,
    isPremium: false,
    sortOrder: 4,
  },
  {
    slug: 'social',
    nameAr: 'استوديو السوشيال',
    nameEn: 'Social Studio',
    descriptionAr: 'محتوى يوتيوب وتيك توك وإنستغرام — سكربتات، هاشتاقات، Hook',
    category: 'text',
    icon: '🎥',
    color: '#ef4444',
    gradient: 'from-red-500 to-pink-600',
    href: '/studios/social',
    isActive: true,
    isPremium: false,
    sortOrder: 5,
  },
  {
    slug: 'channel-analyzer',
    nameAr: 'تحليل القنوات',
    nameEn: 'Channel Analyzer',
    descriptionAr: 'تحليل قناتك وتحسينها — نقاط قوة وضعف، اقتراحات محتوى',
    category: 'text',
    icon: '📊',
    color: '#8b5cf6',
    gradient: 'from-violet-500 to-purple-600',
    href: '/studios/channel-analyzer',
    isActive: true,
    isPremium: false,
    sortOrder: 6,
  },
  {
    slug: 'thumbnails',
    nameAr: 'الصور المصغرة',
    nameEn: 'Thumbnail Studio',
    descriptionAr: 'أفكار ونصوص وprompts لصور مصغرة جذابة',
    category: 'text',
    icon: '🖼️',
    color: '#06b6d4',
    gradient: 'from-cyan-500 to-blue-600',
    href: '/studios/thumbnails',
    isActive: true,
    isPremium: false,
    sortOrder: 7,
  },
  {
    slug: 'images',
    nameAr: 'توليد الصور',
    nameEn: 'Image Studio',
    descriptionAr: 'إنشاء صور إبداعية بالذكاء الاصطناعي — واقعي، كرتوني، سينمائي',
    category: 'image',
    icon: '🎨',
    color: '#ec4899',
    gradient: 'from-pink-500 to-rose-600',
    href: '/studios/images',
    isActive: true,
    isPremium: false,
    sortOrder: 8,
  },
  {
    slug: 'audio',
    nameAr: 'توليد الصوت',
    nameEn: 'Audio Studio',
    descriptionAr: 'تحويل النص إلى صوت — تعليق صوتي احترافي',
    category: 'audio',
    icon: '🔊',
    color: '#14b8a6',
    gradient: 'from-teal-500 to-cyan-600',
    href: '/studios/audio',
    isActive: true,
    isPremium: false,
    sortOrder: 9,
  },
  {
    slug: 'video',
    nameAr: 'توليد الفيديو',
    nameEn: 'Video Studio',
    descriptionAr: 'إنشاء أفكار وسكربتات ومشاهد الفيديو بالذكاء الاصطناعي',
    category: 'video',
    icon: '🎞️',
    color: '#f97316',
    gradient: 'from-orange-500 to-amber-600',
    href: '/studios/video',
    isActive: true,
    isPremium: false,
    sortOrder: 10,
  },
  {
    slug: 'books-tools',
    nameAr: 'الكتب وأدوات AI',
    nameEn: 'Books & AI Tools',
    descriptionAr: 'تلخيص كتب، خطط قراءة، دليل أدوات AI المفيدة',
    category: 'text',
    icon: '📚',
    color: '#84cc16',
    gradient: 'from-lime-500 to-green-600',
    href: '/studios/books-tools',
    isActive: true,
    isPremium: false,
    sortOrder: 11,
  },
]

export const getStudio = (slug: string): StudioConfig | undefined =>
  STUDIOS.find((s) => s.slug === slug)

export const getActiveStudios = (): StudioConfig[] =>
  STUDIOS.filter((s) => s.isActive).sort((a, b) => a.sortOrder - b.sortOrder)
